### ISSUE TITLE
Xamarin.EnableKeyboardEffect "Platform does not exist in the namespace Xamarin.keyboardHelper" Error

### ISSUE THREAD

**Issue by dinobu** [masonyc/Xamarin.KeyboardHelper#12]
Getting this error after I followed your steps on VS2017

**Error	CS0234	The type or namespace name 'Platform' does not exist in the namespace 'Xamarin.KeyboardHelper' (are you missing an assembly reference?)**

**Comment by thudugala** [comment]
@dinobu You need to target Android framework 9.0+

**Comment by dinobu** [comment]
> @dinobu You need to target Android framework 9.0+

Woow, targeting only 10.4% of market ???

**Comment by thudugala** [comment]
@dinobu you can still set your minimum Android Version to 16+, This is just the target Android framework.

We recommend that you **always compile with the latest available Target Framework version**. Doing so provides you with helpful warning messages for any deprecated APIs that might be called by your code. Using the latest Target Framework version is especially important when you use the latest support library releases – each library expects your app to be compiled at that support library's minimum API level or greater.

https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/android-api-levels?tabs=windows#target-framework

Minimum Android Version <= Target Android Version <= Target Framework

**Comment by dinobu** [comment]
@thudugala Thank you.  Would you mind elaboration on effects:KeyboardEffect.RequestFocus functionality (maybe with more info in your documentation).  What is it supposed to do, how, when?
Thanks

**Comment by masonyc** [comment]
In the previous version of the plugin, control that uses the effect will automatically get the focus when view rendered. In version 2.05, control does not automatically get focus anymore, instead if you want to get focus, you have to call the RequestFocus = true in your XAML file.

**Comment by dinobu** [comment]
> In the previous version of the plugin, control that uses the effect will automatically get the focus when view rendered. In version 2.05, control does not automatically get focus anymore, instead if you want to get focus, you have to call the RequestFocus = true in your XAML file.

Thanks, that would be useful info in Wiki

**Comment by dinobu** [comment]
@thudugala Please note that I stil have this error even though target version is set to API 9.0

![Android compile version](https://user-images.githubusercontent.com/40807298/59542817-b305ac00-8ebc-11e9-80e3-9b1c1f65f3be.png)

![Android Missing Platform](https://user-images.githubusercontent.com/40807298/59542844-d16ba780-8ebc-11e9-9661-d1f34ba92293.png)

Please reopen

**Comment by thudugala** [comment]
@dinobu Can you please attach a sample project ?

**Comment by dinobu** [comment]
> @dinobu Can you please attach a sample project ?

Sorry, cant provide my project but I am having this issue even though I have installed API 28 SDK

**Comment by dinobu** [comment]
@thudugala @masonyc I think you require something else in addition to API 28.  I am still having this issue.  Is it specific XF version that you require or something else?

**Comment by thudugala** [comment]
@dinobu can you recreate this issue in a sample project and attach it?

**Comment by dinobu** [comment]
> @dinobu can you recreate this issue in a sample project and attach it?

That's the think, my sample project works fine as I explained above.  But on my project, when I set to API 28 and rebuild, I get
![Android installed api 28 - 2](https://user-images.githubusercontent.com/40807298/59718812-cc19a000-91cf-11e9-8f45-3558314592a5.png)

**Comment by dinobu** [comment]
@thudugala I think you also require XF 4+.  After installing your package and setting to API 28, I started having the issue above.  Restarting VS or cleaning solution and rebuilding did not help at all.
After updating to XF 4+, restarting VS, the issue is gone
