### ISSUE TITLE
Bind boolean property to effect is error

### ISSUE THREAD

**Issue by wangyankun33** [masonyc/Xamarin.KeyboardHelper#20]
### xaml
```
<Entry x:Name="outhead_ProductCode" Placeholder="备件号" effects:KeyboardEffect.EnableKeyboard="{Binding outhead_ProductCode_check}" FontSize="Small" Margin="0,-5,0,0">
  <Entry.Effects>
           <effects:KeyboardEnableEffect/>
 </Entry.Effects>                                                
</Entry>     
```             
### xaml.cs

```
bool outhead_ProductCode_check=false;
private void Outhead_BoxCode_Completed(object sender, EventArgs e)
 {
      outhead_ProductCode.Focus();
      this.outhead_ProductCode_check = true;
 }
```
在enter之后，软键盘的binding 没有生效

**Comment by masonyc** [comment]
你的xaml.cs写的不对 https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-basics/data-bindings-to-mvvm 可以看一下怎么做binding

**Comment by wangyankun33** [comment]
> 你的xaml.cs写的不对 https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-basics/data-bindings-to-mvvm 可以看一下怎么做binding

I wrote this, there is no problem! Now my demand is, after the entry gets the focus, the default does not play the soft keyboard, click on the entry again to display the soft keyboard, may I ask if this is achieved?

**Comment by thudugala** [comment]
@wangyankun33  can you please attach a sample project ?

**Comment by wangyankun33** [comment]
Thank you,Wait for me to give you an example and then reply to you!


------------------ 原始邮件 ------------------
发件人: "Elvin (Tharindu) Thudugala"<notification
s@github.com>;
发送时间: 2019年8月13日(星期二) 下午3:22
收件人: "masonyc/Xamarin.KeyboardHelper"<Xamarin.KeyboardHelper@noreply.github.com>;
抄送: "小飞象"<2603109625@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [masonyc/Xamarin.KeyboardHelper] Bind boolean property to effectis error (#20)




@wangyankun33  can you please attach a sample project ?
