### ISSUE TITLE
Xamarin.KeyboardHelper entry Barcode scanning issue

### ISSUE THREAD

**Issue by uday458** [masonyc/Xamarin.KeyboardHelper#25]
Hi Team,
           Xamarin.KeyBoardHelper hiding keyboard with effects pretty much good.
I have an issue like,I have barcode scanner attached to device and am able to scan barcode using scanner and am not seeing keyboard which is good.

            Issue I found, entry scanning completely slow with barode device scanning..In xaml page am having listview,entry,menu.

**Comment by masonyc** [comment]
hi @uday458 , I don't think your problem is related to this plugin.
