### ISSUE TITLE
Xamarin.Android.Support.Design is not used anymore with AndroidX

### ISSUE THREAD

**Issue by whitedevils** [masonyc/Xamarin.KeyboardHelper#32]
Package to work need to have xamarin.android.support.design library installed. With androidX this library is not used anymore. Is possible to recompile project with androidX support? thanks

**Comment by masonyc** [comment]
@whitedevils  please try 3.0.1

**Comment by Fred7171** [comment]
3.0.1 need NETStandard 2.1. If solution works on UWP/IOS/Android it's not possible use NETStandard 2.1. Could you make work on NETStandard 2.0?
