### ISSUE TITLE
Entry.Unfocused not firing when entry becomes unfocused

### ISSUE THREAD

**Issue by stavroaudi** [masonyc/Xamarin.KeyboardHelper#33]
I want to force Focus on a blank page. If a user taps anywhere on the blank page (whitespace) then the focus is lost, and one way I thought of achieving constant focus is by adding Entry.Focus() on Entry.Unfocused, so if the user taps on the whitespace, focus is lost then refocused immediately, but the Entry.Unfocused event is not executing at all.

**Comment by masonyc** [comment]
not related to this plugin
